<!--DOCTYPE html>
<html id="top" lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Initiation à bootstrap</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">


        <link rel="stylesheet" href="css/style.css"><div id="haut">
	</head>


    <body>
        <header id="header" class="bg-light"-->
        <div class="container">
                <nav>
                    <a href="#"><img src="<?= $wwwUrl ?>/images/HotPizza/logo.jpg" alt="logo"></a>    
                    <a href="#">A la Carte</a>
                    <a href=""><i class="fas fa-map-marked-alt"></i>Trouver votre pizzeria !</a>
                    <a href="#">A emporter</a>
                    <a href="#">Livraison</a>
                    <a href="#"><i class="fas fa-comments"></i>Nous contacter</a>
                    <a href="#"><i class="fas fa-user-plus"></i> S'inscrire</a>
                </nav>
            </div>
        </header>
        <main>
            <section class="home">
                <div class="container">
                <nav>
			        <ul>
				        <li>
					        <a href="#">Pizzas</a>
					        <div class="menu">
						        <div class="sous-menu">
							        <h2>Viandes et poissons</h2>
                                    <ul>
								        <li><a href="#">La Reine</a></li>
								        <li><a href="#">La Savoyarde</a></li>
								        <li><a href="#">La Barbecue</a></li>
								        <li><a href="#">La Poulet</a></li>
								        <li><a href="#">L'American burger</a></li>
								        <li><a href="#">La Saumon</a></li>
							        </ul>
						        </div>
						        <div class="sous-menu">
							        <h2>Végétariennes</h2>
							        <ul>
								        <li><a href="#">La Margherita</a></li>
                                        <li><a href="#">La 4 fromages</a></li>
                                        <li><a href="#">La Chèvre miel</a></li>
                                        <li><a href="#">La Végétarienne</a></li>
							        </ul>
						        </div>
					            </div>
				        </li>
				        <li>
					        <a href="#">Desserts</a>
					        <div class="menu">
						        <div class="sous-menu">
							        <h2>Chocolat maison !</h2>
                                    <ul>
                                        <li><a href="#">Cookie</a></li>
                                        <li><a href="#">Brownie</a></li>
                                        <li><a href="#">Mousse au Chocolat</a></li>
                                    </ul>
                                </div>
						        <div class="sous-menu">
							    <h2>Fruits du potager !</h2>
							        <ul>
								        <li><a href="#">Duo de fruits</a></li>
                                        <li><a href="#">Fromage blanc Framboise</a></li>
							        </ul>
						            </div>
                        </li>
				        <li>
					        <a href="#">Boissons</a>
					        <div class="menu">
						        <div class="sous-menu">
							        <h2>Non Gazeuses</h2>
                                    <ul>
                                        <li><a href="#">Eau </a></li>
                                        <li><a href="#">Brownie</a></li>
                                        <li><a href="#">Mousse au Chocolat</a></li>
                                    </ul>
                                </div>
						        <div class="sous-menu">
							    <h2>Fruits du potager !</h2>
							        <ul>
								        <li><a href="#">Duo de fruits</a></li>
                                        <li><a href="#">Fromage blanc Framboise</a></li>
							        </ul>
						            </div>
