

    <body>
        <header id="header" class="bg-light"-->
        <div class="container">
                <nav>
                    <a href="#"><img src="<?= $wwwUrl ?>/images/HotPizza/logo.jpg" alt="logo"></a>    
                    <a href="#">A la Carte</a>
                    <a href=""><i class="fas fa-map-marked-alt"></i>Trouver votre pizzeria !</a>
                    <a href="#">A emporter</a>
                    <a href="#">Livraison</a>
                    <a href="#"><i class="fas fa-comments"></i>Nous contacter</a>
                    <a href="#"><i class="fas fa-user-plus"></i> S'inscrire</a>
                </nav>
            </div>
        </header>
        <main>
            <section class="home">
                <div class="container">
                <nav>
			        <ul>
				        <li>
					        <a href="#">Pizzas</a>
					        <div class="menu">
						        <div class="sous-menu">
							        <h2>Viandes et poissons</h2>
                                    <ul>
								        <li><a href="#">La Reine</a></li>
								        <li><a href="#">La Savoyarde</a></li>
								        <li><a href="#">La Barbecue</a></li>
								        <li><a href="#">La Poulet</a></li>
								        <li><a href="#">L'American burger</a></li>
								        <li><a href="#">La Saumon</a></li>
							        </ul>
						        </div>
						        <div class="sous-menu">
							        <h2>Végétariennes</h2>
							        <ul>
								        <li><a href="#">La Margherita</a></li>
                                        <li><a href="#">La 4 fromages</a></li>
                                        <li><a href="#">La Chèvre miel</a></li>
                                        <li><a href="#">La Végétarienne</a></li>
							        </ul>
						        </div>
					            </div>
				        </li>
				        <li>
					        <a href="#">Desserts</a>
					        <div class="menu">
						        <div class="sous-menu">
							        <h2>Chocolat maison !</h2>
                                    <ul>
                                        <li><a href="#">Cookie</a></li>
                                        <li><a href="#">Brownie</a></li>
                                        <li><a href="#">Mousse au Chocolat</a></li>
                                    </ul>
                                </div>
						        <div class="sous-menu">
							    <h2>Fruits du potager !</h2>
							        <ul>
								        <li><a href="#">Duo de fruits</a></li>
                                        <li><a href="#">Fromage blanc Framboise</a></li>
							        </ul>
						            </div>
                        </li>
				        <li>
					        <a href="#">Boissons</a>
					        <div class="menu">
						        <div class="sous-menu">
							        <h2>Non Gazeuses</h2>
                                    <ul>
                                        <li><a href="#">Vittel 33cl</a></li>
                                        <li><a href="#">Vittel 1L5</a></li>
                                        <li><a href="#">Ice Tea pêche 33cl</a></li>
                                        <li><a href="#">Ice Tea pêche 1L5</a></li>
                                        <li><a href="#">Oasis tropical 33cl</a></li>
                                    </ul>
                                </div>
						        <div class="sous-menu">
							    <h2>Gazeuses</h2>
							        <ul>
								        <li><a href="#">Perrier 50cl</a></li>
                                        <li><a href="#">Pepsi 33cl</a></li>
                                        <li><a href="#">Pepsi 1L5</a></li>
                                        <li><a href="#">Pepsi Max 33cl</a></li>
                                        <li><a href="#">Pepsi Max 1L5</a></li>
                                        <li><a href="#">Orangina 33cl</a></li>
                                        <li><a href="#">7up 33cl</a></li>
							        </ul>
						            </div>
