 
        <div class="bannerto"></div>   
    
            
        <nav class="menuderoulant">
            <ul>
                <li>
                    <a href="#">Pizzas</a>
                    <div class="menu">
                        <div class="sous-menu">
                            <h2>Viandes et poissons</h2>
                            <ul>
                                <li><a href="#">La Reine</a></li>
                                <li><a href="#">La Savoyarde</a></li>
                                <li><a href="#">La Barbecue</a></li>
                                <li><a href="#">La Poulet</a></li>
                                <li><a href="#">L'American burger</a></li>
                                <li><a href="#">La Saumon</a></li>
                            </ul>
                        </div>
                        <div class="sous-menu">
                            <h2>Végétariennes</h2>
                            <ul>
                                <li><a href="#">La Margherita</a></li>
                                <li><a href="#">La 4 fromages</a></li>
                                <li><a href="#">La Chèvre miel</a></li>
                                <li><a href="#">La Végétarienne</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="#">Desserts</a>
                    <div class="menu">
                        <div class="sous-menu">
                            <h2>Chocolat maison !</h2>
                            <ul>
                                <li><a href="#">Cookie</a></li>
                                <li><a href="#">Brownie</a></li>
                                <li><a href="#">Mousse au Chocolat</a></li>
                            </ul>
                        </div>
                        <div class="sous-menu">
                        <h2>Fruits du potager !</h2>
                            <ul>
                                <li><a href="#">Duo de fruits</a></li>
                                <li><a href="#">Fromage blanc Framboise</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="#">Boissons</a>
                    <div class="menu">
                        <div class="sous-menu">
                            <h2>Non Gazeuses</h2>
                            <ul>
                                <li><a href="#">Vittel 33cl</a></li>
                                <li><a href="#">Vittel 1L5</a></li>
                                <li><a href="#">Ice Tea pêche 33cl</a></li>
                                <li><a href="#">Ice Tea pêche 1L5</a></li>
                                <li><a href="#">Oasis tropical 33cl</a></li>
                            </ul>
                        </div>
                        <div class="sous-menu">
                        <h2>Gazeuses</h2>
                            <ul>
                                <li><a href="#">Perrier 50cl</a></li>
                                <li><a href="#">Pepsi 33cl</a></li>
                                <li><a href="#">Pepsi 1L5</a></li>
                                <li><a href="#">Pepsi Max 33cl</a></li>
                                <li><a href="#">Pepsi Max 1L5</a></li>
                                <li><a href="#">Orangina 33cl</a></li>
                                <li><a href="#">7up 33cl</a></li>
                            </ul>
                        </div>
                    </div>  
                </li>
            </ul>
        </nav>
    

    <section class="carte">
        <h1>A la carte !</h1>
        <div>
            <article id="reine" class="container-fluid reine bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Reine</h2>

                        <p class="lead mb-0">
                        Sauce tomate, mozzarella, jambon, champignon 
                        </p>
                    </div>
                </div>
            </article>

            <article id="savoyarde" class="container-fluid savoyarde bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Savoyarde</h2>

                        <p class="lead mb-0">
                            Sauce crémée, mozzarella, fromage à raclette, pommes de terre, bacon, oignons 
                        </p>
                    </div>
                </div>
            </article>

            <article id="barbecue" class="container-fluid barbecue bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Barbecue</h2>

                        <p class="lead mb-0">
                            Sauce tomate, mozzarella, bœuf haché, merguez, poulet, bacon, sauce barbecue chipotle légèrement pimentée 
                        </p>
                    </div>
                </div>
            </article>
        
            <article id="poulet" class="container-fluid poulet bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Poulet</h2>

                        <p class="lead mb-0">
                            Sauce crémée, mozzarella, poulet, poivron, sauce texas grill, oignons frits
                        </p>
                    </div>
                </div>
            </article>
            <article id="americanbg" class="container-fluid americainebg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>L'American burger</h2>

                        <p class="lead mb-0">
                            Sauce crémée, mozzarella, bœuf hâché, cheddar, tomate, oignon, sauce cocktail, origan
                        </p>
                    </div>
                </div>
            </article>
            <article id="saumon" class="container-fluid saumon bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Saumon</h2>

                        <p class="lead mb-0">
                            Sauce crémée, mozzarella, pesto, saumon fumé, citron, origan 
                        </p>
                    </div>
                </div>
            </article>
            <article id="marg" class="container-fluid marg bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Margherita</h2>

                        <p class="lead mb-0">
                        Sauce tomate, mozzarella, olives noires 
                        </p>
                    </div>
                </div>
            </article>
            <article id="qfr" class="container-fluid qfr bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La 4 Fromages</h2>

                        <p class="lead mb-0">
                            Sauce crémée, mozzarella, chèvre, gorgonzola, parmesan (grana padano), origan
                        </p>
                    </div>
                </div>
            </article>
            <article id="chevre" class="container-fluid chevre bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Chèvre</h2>

                        <p class="lead mb-0">
                            Sauce crémée, mozzarella, chèvre, miel (au choix)
                        </p>
                    </div>
                </div>
            </article>
            <article id="vege" class="container-fluid vege bg-white">
                <div class="row">
                    <div class="col-lg-6 bg-showcase order-lg-1">
                    </div>

                    <div class="col-lg-6 my-auto">
                        <h2>La Végétarienne</h2>

                        <p class="lead mb-0">
                            Sauce tomate, mozzarella, légumes grillés (courgette, aubergine, poivron rouge et jaune), tomate, huile d'olive aromatisée au basilic et à l'ail
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </section>
