

            
        
        
        
        
       
            <section class="banner">
                <h1>Bienvenue chez Hot Pizza</h1>
            </section>
            <section class="moyenssect">
                <h2 class="avec">Avec Hot Pizzas vous pouvez manger :</h2>
                <div class="container">
                    <article class="moyensart">
                    
                        <h3><span>Sur place</h3></span>
                        <p><i class="fas fa-utensils"></i></p>
                        <p>
                            Hot pizza propose 20 restaurants en Europe dont 7 en France
                        </p>
                    </article>

                    <article class="moyensart">
                        <h3><span>A emporter</span></h3>
                        <p><i class="fas fa-shopping-bag"></i></p>
                        <p>
                            Mais aussi, nous vous proposons de commander en ligne ou par téléphone dans le restaurant de votre choix afin de recupérer vos pizzas prêtes à être dégustées !
                        </p>
                    </article>

                    <article class="moyensart">
                        <h3><span>Vous faire livrer</span></h3>
                        <p><i class="fas fa-truck-moving"></i></p>
                        <p>
                            <b>Nouveauté!</b> Vous pouvez désormais vous faire livrer vos pizzas chez vous !
                        </p>
                    </article>
                </div>
            </section>  
        
        
       






