<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->

    <header>  
        <div id="haut">
            <div id="haut_body">
                <img id="logo" src=" <?= $wwwUrl ?>/images/HotPizza/logo.jpg" alt="logo">
                <nav class="home">   
                    <a href="<?= $requestUrl ?>/carte">A la Carte</a>
                    <a href=""><i class="fas fa-map-marked-alt"></i>Trouver votre pizzeria !</a>
                    <a href="#">A emporter</a>
                    <a href="#">Livraison</a>
                    <a href="#"><i class="fas fa-comments"></i>Nous contacter</a>
                    <a href="#">Se connecter</a>
                </nav>
            </div>
        </div>
        </header>
        
        
        
        
        
        <main>
            <section class="banner">
                <h1>Bienvenue à hot pizzas</h1>
            </section>
            <section class="moyenssect">
                <h2 class="avec">Avec Hot Pizzas vous pouvez manger :</h2>
                <div class="container">
                    <article class="moyensart">
                    
                        <h3><span>Sur place</h3></span>
                        <p><i class="fas fa-utensils"></i></p>
                        <p>
                            Hot pizza propose 20 restaurants en Europe dont 7 en France
                        </p>
                    </article>

                    <article class="moyensart">
                        <h3><span>A emporter</span></h3>
                        <p><i class="fas fa-shopping-bag"></i></p>
                        <p>
                            mais aussi, nous vous proposons de commander en ligne ou par téléphone dans le restaurant de votre choix afin de recupérer vos pizzas prêtes à être dégustées !
                        </p>
                    </article>

                    <article class="moyensart">
                        <h3><span>Vous faire livrer</span></h3>
                        <p><i class="fas fa-truck-moving"></i></p>
                        <p>
                            <b>Nouveauté!</b> Vous pouvez désormais vous faire livrer vos pizzas chez vous !
                        </p>
                    </article>
                </div>
            </section>  
        
        
        </main>





</body
