<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->

    <header>  
        <div id="haut">
            <div id="haut_body">
                <img id="logo" src=" <?= $wwwUrl ?>/images/HotPizza/logo.jpg" alt="logo">
                <nav class="home">   
                    <a href="<?= $requestUrl ?>/carte">A la Carte</a>
                    <a href=""><i class="fas fa-map-marked-alt"></i>Trouver votre pizzeria !</a>
                    <a href="#">A emporter</a>
                    <a href="#">Livraison</a>
                    <a href="#"><i class="fas fa-comments"></i>Nous contacter</a>
                    <a href="#"><i class="fas fa-user-plus"></i> S'inscrire</a>
                </nav>
            </div>
        </div>
        </header>
        
        
        
        
        
        <main>
            <section class="banner">
            <h1>Bienvenue chez Hot Pizza</h1>
            </section>
            <section class="homedeux"></section>
        
        
        </main>





</body
