<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hot Pizza</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Lacquer|Lobster|Orbitron|Roboto+Mono&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">



    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/menusousmenu.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/carte.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/headerfooter.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
    <body class="<?= $bodyClass ?>">
        <header>
            <div id="haut">
                <div id="haut_body">
                    <img id="logo" src=" <?= $wwwUrl ?>/images/HotPizza/logo.jpg" alt="logo">
                    <?php if (isset($_SESSION['user']) && $_SESSION['user']['role'] === 'admin') : ?>
                    <nav class="fixed">
                        <a href="<?= $requestUrl ?>/carte">A la Carte</a>
                        <a href=""><i class="fas fa-map-marked-alt"></i>Trouver votre pizzeria !</a>
                        <a href="#">A emporter</a>
                        <a href="#"id="livraison">Livraison</a>
                        <a href="#"><i class="fas fa-comments"></i>Nous contacter</a>
                        <?php if (!isset($_SESSION['user'])) : ?>
                        <a href="<?= $requestUrl ?>/register">Se connecter</a>
                    <?php else : ?>
                    <a id="deconnexion" href="<?= $requestUrl ?>/logout">Déconnexion (<?= $_SESSION['user']['firstName'] ?>)
                    </a>
                    <?php endif ?>
                    </nav>
                    <?php else : ?>
                    <nav class="fixed">
                        <a href="<?= $requestUrl ?>/carte">A la Carte</a>
                        <a href=""><i class="fas fa-map-marked-alt"></i>Trouver votre pizzeria !</a>
                        <a href="#">A emporter</a>
                        <a href="#"id="livraison">Livraison</a>
                        <a href="#"><i class="fas fa-comments"></i>Nous contacter</a>
                    <?php if (!isset($_SESSION['user'])) : ?>
                        <a href="<?= $requestUrl ?>/login">Se connecter</a>
                    <?php else : ?>
                    <a id="deconnexion" href="<?= $requestUrl ?>/logout">Déconnexion (<?= $_SESSION['user']['firstName'] ?>)</a>
                    <?php endif ?>
                    <?php endif ?>
                    </nav>
                </div>
            </div>
        </header>
        <main>    
            <?php include $this->viewData['template'] ?>
        </main>
    </body>
</html>


