
    <header>
        <h1>Se connecter</h1>
    </header>

    <main>
    <section>
        <form action="<?= $requestUrl ?>/login" method="POST">
            <label for="login">Pseudo :</label>
            <input type="text" name="login">
            <br>
            <label for="password">Mot de passe :</label>
            <input type="text" name="password">
            <br>
            <input type="hidden" name="case" value="create-user">
            <input id="valider" type="submit" value="Valider">
        </form>
    </section>

    <section>
        <h2>S'inscrire</h2>
        <form action="" method="POST">
            <label for="firstName">Prénom :</label>
            <input type="text" name="firstName">
            <br>
            <label for="lastName">Nom :</label>
            <input type="text" name="lastName">
            <br>
            <label for="login">Pseudo :</label>
            <input type="text" name="login">
            <br>
            <label for="password">Mot de passe :</label>
            <input type="text" name="password">
            <br>
            <label for="mail">E-mail :</label>
            <input type="text" name="mail">
            <br>
            <input type="hidden" name="case" value="create-user">
            <input id="valider" type="submit" value="Valider">
        </form>
    </section>


