<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>S'inscrire :</h1>
    </header>

    <main>
    <section>
        <form action="" method="POST">
            <label for="firstName">Prénom :</label>
            <input type="text" name="firstName">
            <br>
            <label for="lastName">Nom :</label>
            <input type="text" name="lastName">
            <br>
            <label for="login">Pseudo :</label>
            <input type="text" name="login">
            <br>
            <label for="password">Mot de passe :</label>
            <input type="text" name="password">
            <br>
            <label for="mail">E-mail :</label>
            <input type="text" name="mail">
            <br>
            <input type="hidden" name="case" value="create-user">
            <input id="valider" type="submit" value="Valider">
        </form>
    </section>
  </main>
</body>
</html>