<h1>Préparez votre formule..</h1>

	<?php foreach ($formules as $formule) :?>
		<button id="formule" data-id="<?= $formule['id']?>" data-entree="<?= $formule['starter']?>" data-dessert="<?= $formule['dessert']?>" data-boisson="<?= $formule['drink']?>"><?= $formule['name']?> 
		(
		<?php if($formule['starter']):?>Entrée+ <?php endif;?>
		Plat
		<?php if($formule['drink']):?>+ Boisson<?php endif;?>
		<?php if($formule['dessert']):?>+ Dessert<?php endif;?>
		)
		</button>
	<?php endforeach;?>
<fieldset>
	<legend>Plat</legend>
	
	<fieldset>
		<legend>Ingrédient</legend>
	</fieldset>
</fieldset>
<script src="formule.js"></script>