	

	<?php foreach ($formules as $formule) :?>
		<button class="formule" data-id="<?= $formule['id']?>" data-entree="<?= $formule['starter']?>" data-dessert="<?= $formule['dessert']?>" data-boisson="<?= $formule['drink']?>"><?= $formule['name']?> 
		(
		<?php if($formule['starter']):?>Entrée+ <?php endif;?>
		Plat
		<?php if($formule['drink']):?>+ Boisson<?php endif;?>
		<?php if($formule['dessert']):?>+ Dessert<?php endif;?>
		)
		</button>
	<?php endforeach;?>


<h1><i class="fa fa-shopping-cart"></i> Préparez votre formule..</h1>

<section class="dish hide">
	<table>
		<tr>
			<td>
				<fieldset id="dish">
					<legend>Repas</legend>
					<table>
						<tr>
						<?php foreach ($bases as $base) :?>
								<td>
									<?=$base['name']?>
								</td>
								<td>
									<input type="radio" name="dish" value="$base['id']" class="dishSelect">
								</td>
								<td>
									<img class="repas" src="<?=$wwwUrl.'/images/'.$base['image']?>" alt="<?=$base['name']?>"><br>
									<strong><?=number_format($base['unitPrice'],2)?> €</strong>
								</td>
							</tr>
						<?php endforeach;?>	
					</table>
					
				</fieldset>
			</td>
			<td>
				<fieldset id="dish">
					<legend>Ingrédients</legend>
					<table>
						<tr>
						<?php foreach ($ingredients as $ingredient) :?>
								<td>
									<strong>[<?= $ingredient['ingredient']?>]</strong>
									<?=$ingredient['name']?>
								</td>
								<td>
									<input type="checkbox" name="ingredient[]" value="$ingredient['id']" class="dishSelect">
								</td>
								<td>
									<img class="repas" src="<?=$wwwUrl.'/images/'.$ingredient['image']?>" alt="<?=$ingredient['name']?>">
									<br>
									<strong><?= $ingredient['unitPrice']== 0 ? 'Gratuit' : number_format($ingredient['unitPrice'],2) . '€'?> </strong>
								</td>
							</tr>
						<?php endforeach;?>	
					</table>
					
				</fieldset>
			</td>
		</tr>
	</table>

	<form data-order-step="run" id="order-form" class="generic-form hidden">

	    <fieldset id="taille-image">
	        <legend>Ajouter un article</legend>
	        <ul>
	            <li>
	                <label for="meal">Nom :</label>
	                <select id="meal" name="meal">
	                    
	                </select>
	                <article id="meal-details" class="meal-details no-left-label">
	                    <img src="" alt="Photo du produit">
	                    <p></p>
	                    <span>Prix : <strong></strong></span>
	                </article>
	            </li>
	            <li>
	                <label for="quantity">Quantité :</label>
	                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required><strong id='alert'></strong>
	            </li>
	            <li>
	                <button class="button button-primary no-left-label" type="submit">Ajouter</button>
	            </li>
	        </ul>
	    </fieldset>

	    <fieldset>
	        <legend>Récapitulatif de la commande</legend>
	        <section id="order-summary"></section>
	    </fieldset>
	</form>

	<ul class="link-list">
	    <li>
	        <button id="validate-order" class="button button-primary" disabled>Valider la commande</button>
	        <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
	    </li> 
	</ul>

</section>


<script src="<?= $wwwUrl ?>/js/formule.js"></script>